from .breadcrumbs import BreadcrumbsLocators  # noqa
from .cookies import CookiesLocators  # noqa
from .filter import FilterPageLocators  # noqa
from .footer import FooterLocators  # noqa
from .header import HeaderPageLocators  # noqa
from .navbar import NavBarLocators  # noqa
from .vacancies.filter_menu import VacancyFiltersMenuLocators  # noqa
from .vacancies.filter_vacancies import FilterVacanciesLocators  # noqa
from .vacancies.list import VacanciesListLocators  # noqa
from .vacancies.response_form import VacancyResponseFormLocators  # noqa
from .vacancies.vacancy import VacancyItemLocators  # noqa
