from .breadcrumbs import BreadcrumbsLocators
from .cookies import CookiesLocators
from .filter import FilterPageLocators
from .footer import FooterLocators
from .header import HeaderPageLocators
from .navbar import NavBarLocators
from .vacancies.filter_menu import VacancyFiltersMenuLocators
from .vacancies.filter_vacancies import FilterVacanciesLocators
from .vacancies.list import VacanciesListLocators
from .vacancies.response_form import VacancyResponseFormLocators
from .vacancies.vacancy import VacancyItemLocators
