name: UI Tests & Allure Report

# Триггеры: push и PR в main
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

# Глобальные переменные
env:
  PYTHON_VERSION: "3.11"
  ALLURE_RESULTS_DIR: "./allure-ui-results"
  ALLURE_REPORT_DIR: "./allure-ui-report"
  ALLURE_HISTORY_DIR: "./allure-ui-history"

jobs:

  # 🧪 Запуск UI-тестов через Playwright
  ui-tests:
    runs-on: ubuntu-latest
    steps:

      # 1. Checkout репозитория
      - name: 📥 Checkout repository
        uses: actions/checkout@v4

      # 2. Кэширование pip-зависимостей (ускоряет повторные запуски)
      - name: 💾 Cache pip dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      # 3. Кэширование браузеров Playwright (опционально, но полезно)
      - name: 💾 Cache Playwright browsers
        uses: actions/cache@v3
        with:
          path: ~/.cache/ms-playwright
          key: ${{ runner.os }}-playwright-browsers

      # 4. Установка Python
      - name: 🐍 Set up Python ${{ env.PYTHON_VERSION }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      # 5. Создание необходимых директорий (логи, видео, отчёты и т.д.)
      - name: 🗂️ Create required directories
        run: |
          mkdir -p ${{ env.ALLURE_RESULTS_DIR }} videos tracing logs
          touch browser_state.json
          echo "✅ Directories and files created"

      # 6. Установка зависимостей + Playwright
      - name: 📦 Install dependencies and Playwright
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          playwright install --with-deps

      # 7. Запуск тестов с генерацией Allure-результатов
      - name: 🧪 Run UI tests with pytest
        run: |
          pytest -m UI \
            --alluredir=${{ env.ALLURE_RESULTS_DIR }} \
            --numprocesses=2 \


      # 8. Архивация результатов (даже если тесты упали)
      - name: 📤 Upload Allure results artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: allure-ui-results
          path: ${{ env.ALLURE_RESULTS_DIR }}

  # 📊 Публикация Allure-отчёта на GitHub Pages
  publish-report:
    name: 📈 Publish Allure Report to GitHub Pages
    needs: ui-tests
    if: always()
    runs-on: ubuntu-latest
    steps:

      # 1. Checkout репозитория (основная ветка)
      - name: 📥 Checkout main branch
        uses: actions/checkout@v4

      # 2. Скачиваем артефакт с результатами тестов
      - name: 📥 Download Allure results from ui-tests job
        uses: actions/download-artifact@v4
        with:
          name: allure-ui-results
          path: ${{ env.ALLURE_RESULTS_DIR }}

      # 3. Checkout ветки gh-pages (если есть) для получения истории
      #    continue-on-error: true — если ветки нет, не падаем
      - name: 📥 Checkout gh-pages branch for history
        uses: actions/checkout@v4
        if: always()
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages

      # 4. Генерация Allure-отчёта из результатов
      - name: 📊 Generate Allure Report with history support
        uses: simple-elf/allure-report-action@v1.7
        with:
          allure_results: ${{ env.ALLURE_RESULTS_DIR }}
          allure_report: ${{ env.ALLURE_REPORT_DIR }}
          allure_history: ${{ env.ALLURE_HISTORY_DIR }}

      # # 5. Копируем историю из предыдущего отчёта (если есть)
      # - name: 🔄 Copy previous history into report
      #   run: |
      #     mkdir -p ${{ env.ALLURE_HISTORY_DIR }}
      #     if [ -d "gh-pages/history" ]; then
      #       cp -r gh-pages/history/* ${{ env.ALLURE_HISTORY_DIR }}/ 2>/dev/null || echo "⚠️ No files to copy from previous history"
      #       echo "✅ Copied previous history for trends"
      #     else
      #       echo "ℹ️ No previous history found — starting fresh"
      #     fi

      # 6. Публикация отчёта в ветку gh-pages
      - name: 🚀 Deploy Allure Report to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ${{ env.ALLURE_HISTORY_DIR }}

      # 7. (Опционально) Вывод ссылки на отчёт
      - name: 🔗 Print report URL
        run: |
          echo "✅ Allure Report published!"
          echo "👉 View report at: https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}/"