name: UI Tests & Allure Report

# Триггеры: push и PR в main
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

# Глобальные переменные
env:
  PYTHON_VERSION: "3.11"
  ALLURE_RESULTS_DIR: "./allure-results"
  ALLURE_REPORT_DIR: "./allure-report"
  ALLURE_HISTORY_DIR: "./allure-history"

jobs:

  # 🧪 Запуск UI-тестов через Playwright
  ui-tests:
    runs-on: ubuntu-latest
    steps:

      # 1. Checkout репозитория
      - name: 📥 Checkout repository
        uses: actions/checkout@v4

      # 2. Кэширование pip-зависимостей (ускоряет повторные запуски)
      - name: 💾 Cache pip dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      # 3. Кэширование браузеров Playwright (опционально, но полезно)
      - name: 💾 Cache Playwright browsers
        uses: actions/cache@v3
        with:
          path: ~/.cache/ms-playwright
          key: ${{ runner.os }}-playwright-browsers

      # 4. Установка Python
      - name: 🐍 Set up Python ${{ env.PYTHON_VERSION }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      # 5. Создание необходимых директорий (логи, видео, отчёты и т.д.)
      - name: 🗂️ Create required directories
        run: |
          mkdir -p ${{ env.ALLURE_RESULTS_DIR }} videos tracing logs
          touch browser_state.json
          echo -e "\033[32m✅ Directories and files created\033[0m"

      # 6. Установка зависимостей + Playwright
      - name: 📦 Install dependencies and Playwright
        run: |
          echo "🔧 Upgrading pip..."
          python -m pip install --upgrade pip
          echo "📦 Installing requirements..."
          pip install -r requirements.txt
          echo "🤖 Installing Playwright browsers..."
          playwright install --with-deps
          echo -e "\033[32m✅ Dependencies installed\033[0m"

      # 7. Запуск тестов с генерацией Allure-результатов
      - name: 🧪 Run UI tests with pytest
        run: |
          pytest -m UI \
            --alluredir=${{ env.ALLURE_RESULTS_DIR }} \
            --numprocesses=2 \
            --tb=short
          echo -e "\033[32m✅ UI tests completed\033[0m"

      # 🔄 8. Восстановление истории coverage
      - name: 🔄 Restore Coverage history
        uses: actions/cache/restore@v4
        with:
          path: coverage-history.json
          key: coverage-history-${{ github.run_id }}
          restore-keys: |
            coverage-history-

      # 📊 9. Генерация coverage-отчёта
      - name: 📊 Generate Coverage report
        if: always()
        run: |
          echo "📊 Generating UI Coverage report..."
          ui-coverage-tool save-report
          echo "✅ Coverage report saved to coverage.html"
          echo -e "\033[32m📈 Coverage history saved to coverage-history.json\033[0m"

      # 💾 10. Кэширование истории coverage
      - name: 💾 Cache Coverage history
        if: always()
        uses: actions/cache/save@v4
        with:
          path: coverage-history.json
          key: coverage-history-${{ github.run_id }}

      # 📤 11. Загрузка coverage-отчёта как артефакта
      - name: 📤 Upload Coverage report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: coverage.html

      # 📤 12. Архивация результатов Allure
      - name: 📤 Upload Allure results artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: allure-results
          path: ${{ env.ALLURE_RESULTS_DIR }}

  # 📊 Публикация Allure-отчёта на GitHub Pages
  publish-report:
    name: 📈 Publish Allure Report to GitHub Pages
    needs: ui-tests
    if: always()
    runs-on: ubuntu-latest
    steps:

      # 1. Checkout репозитория (основная ветка)
      - name: 📥 Checkout main branch
        uses: actions/checkout@v4

      # 2. Скачиваем артефакт с результатами тестов
      - name: 📥 Download Allure results from ui-tests job
        uses: actions/download-artifact@v4
        with:
          name: allure-results
          path: ${{ env.ALLURE_RESULTS_DIR }}

      # 📥 3. Checkout gh-pages для истории
      - name: 📥 Checkout gh-pages branch for history
        uses: actions/checkout@v4
        if: always()
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages

      # 📊 4. Генерация Allure-отчёта
      - name: 📊 Generate Allure Report with history support
        uses: simple-elf/allure-report-action@v1.7
        with:
          allure_results: ${{ env.ALLURE_RESULTS_DIR }}
          allure_report: ${{ env.ALLURE_REPORT_DIR }}
          allure_history: ${{ env.ALLURE_HISTORY_DIR }}

      # 5. Деплой отчёта на GitHub Pages
      - name: 🚀 Deploy Allure Report to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ${{ env.ALLURE_HISTORY_DIR }}

      # 🔗 6. Вывод ссылки на отчёт
      - name: 🔗 Print report URL
        run: |
          echo -e "\033[32m✅ Allure отчет опубликован!\033[0m"
          echo -e "\033[34m👉 Отчет доступен по ссылке: https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}/\033[0m"
          echo "📌 Coverage отчет сохранен в артефактах 'coverage-report'"